- hosts: localhost  
  roles:
  - { role: common, tags: common }
  - { role: java, tags: java }
  - { role: docker, tags: docker }
  - { role: maven, local_ansible_data_path: '/tmp/ansible', maven_version: 3.3.3, maven_default: True, tags: maven_3.3 }
  - { role: maven, local_ansible_data_path: '/tmp/ansible', maven_version: 3.2.5, maven_default: True, tags: maven_3.2 }
  - { role: maven, local_ansible_data_path: '/tmp/ansible', maven_version: 3.1.1, tags: maven_3.1 }
  - { role: maven, local_ansible_data_path: '/tmp/ansible', maven_version: 3.0.5, tags: maven_3.0 }
  - { role: scm, tags: scm }
  - { role: nodejs, tags: nodejs }
  - { role: jenkins, tags: jenkins }
