- name: ensure Epel is installed
  yum: name=epel-release

- name: ensure unarchive binaries are present
  yum: name={{ item }} state=installed
  with_items:
  - unzip
  - tar
  - wget

- name: ensure /var/lib/exported exists
  file: path=/var/lib/exported state=directory

- name: ensure user jenkins is present
  user: name=jenkins comment="Jenkins user" uid=1000 home=/var/jenkins_home

