- name: update all packages
  yum: name=* state=latest

- name: ensure Epel is installed
  yum: name=epel-release

- name: ensure unarchive binaries are present
  yum: name={{ item }} state=installed
  with_items:
  - unzip
  - tar
  - wget
  - curl

- name: ensure user jenkins is present
  user: name=jenkins comment="Jenkins user" uid=1000 home=/var/jenkins_home

