- name: install docker binary
  get_url: url=https://get.docker.com/builds/Linux/x86_64/docker-latest dest=/usr/bin/docker mode=0755

- name: "install docker compose (v{{ docker_compose_version }})"
  get_url: url=https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64 dest=/usr/bin/docker-compose mode=0755

